# Generated by Django 3.1.5 on 2021-04-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedata',
            name='instructions',
            field=models.TextField(),
        ),
    ]
