# Generated by Django 3.2 on 2021-04-13 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210413_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='generated_text',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')]),
        ),
    ]
