# Generated by Django 3.2 on 2021-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210413_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_length',
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.TextField(default='Empty'),
        ),
    ]
