# Generated by Django 3.2 on 2021-04-13 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210413_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetype',
            name='recipe_type',
            field=models.CharField(choices=[('salad', 'Salad'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='salad', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')]),
        ),
    ]
